name: "Windows build & upload"

on:
  push:
    branches: [ master ]
    paths-ignore:
      - README.md
      - .gitignore

env:
  BUILD_TYPE: Release

jobs:
  Windows:
    strategy:
      fail-fast: false
      matrix:
        config:
          - os: windows
            os_version: latest
            qt_version: 6.2.0
            arch: x64

    runs-on: ${{ matrix.config.os }}-${{ matrix.config.os_version }}

    steps:
      - uses: actions/checkout@v2

      - name: Cache Qt
        id: cache-qt
        uses: actions/cache@v1
        with:
          path: ../Qt
          key: ${{ matrix.config.os }}-${{ matrix.config.arch }}-${{ matrix.config.qt_version }}-QtCache

      - name: Install Qt
        uses: jurplel/install-qt-action@v2
        with:
          version: ${{ matrix.config.qt_version }}
          arch: ${{ matrix.config.qt_arch }}
          cached: ${{ steps.cache-qt.outputs.cache-hit }}

      - name: Install Conan
        id: conan
        uses: turtlebrowser/get-conan@main

      - name: Prepare dev cmd
        uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: ${{ matrix.config.arch }}

      - name: Install Conan packages
        run: |
          mkdir ${{github.workspace}}\build
          conan install ${{github.workspace}}\conanfile.txt -s build_type=Release -if ${{github.workspace}}\build

      - name: Configure CMake
        run: cmake -B ${{github.workspace}}\build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

      - name: Build
        run: |
          cmake --build ${{github.workspace}}\build --config ${{env.BUILD_TYPE}}
          ls ${{github.workspace}}\build

      - name: Package Qt/QML
        run: |
          windeployqt.exe ${{github.workspace}}\build\bin\yeectl.exe --qmldir ${{github.workspace}}\ --no-translations
          7z a ${{github.workspace}}\build\yeectl.zip ${{github.workspace}}\build\bin\*
          ls ${{github.workspace}}\build\

      - name: Upload release
        uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN  }}
          automatic_release_tag: continuous-win
          prerelease: true
          files: build/yeectl.zip

